### ISSUE TITLE
Add to homescreen saves URL parameters instead of using default page

### ISSUE THREAD

**Issue by netjordanlee** [laithserhan/search#4]

**Comment by laithserhan** [comment]
Users can now Add to home screen so long as search is empty, so far, I cannot find a way to clear the URL parameters when a user invokes add Add to home screen on their mobile device.

As long as the search is empty, the URL parameters reset to search query = empty "?q=" and page to 0 "&p=0"

Will keep investigating other possible solutions.

**Comment by laithserhan** [comment]
closing issue #4 as it seems to be fixed, saving to home screen for both iOS and Android while url parameters are populated now loads default page and also saves last page state as per commit d7b0c6b4bbfd1b347276c153b060920521d17248 and commit 4db931b175672bf67bbc0a36fe1878df43e2f94c
