### ISSUE TITLE
Reset page counter on empty search results

### ISSUE THREAD

**Issue by TheRealZuriki** [laithserhan/search#5]
Reproduce:
1. Search with matching results
2. Replace search with [space][space] or "ZZ"
3. Page combo box still lists old page count

**Comment by laithserhan** [comment]
Page count issue resolved.

Now need implement code to keep page nav buttons disable on false search results to match page nav setup of single page search results.

**Comment by laithserhan** [comment]
no results, no navigation https://github.com/laithserhan/search/commit/db81a9721232898eff2cc2d10d624e3591321169
